# Generated by Django 4.1 on 2024-07-26 09:54

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_rename_userprofile_profile"),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("user", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="post_images")),
                ("caption", models.TextField()),
                ("created_at", models.DateTimeField(default=datetime.datetime.now)),
                ("no_of_likes", models.ImageField(default=0, upload_to="")),
            ],
        ),
    ]
